# Generated by Django 3.0.3 on 2020-02-29 14:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('uri',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='mapquiz.Uri')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('uri',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='mapquiz.Uri')),
                ('hint', models.TextField(max_length=1000)),
                ('found_text', models.TextField(max_length=1000)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='map location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('uri',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='mapquiz.Uri')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('hunt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='mapquiz.Hunt')),
                ('last_location',
                 models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='mapquiz.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('uri',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='mapquiz.Uri')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('stage', models.IntegerField()),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapquiz.Hunt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='location',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='mapquiz.Quiz'),
        ),
    ]
