# Generated by Django 3.0.3 on 2020-03-02 16:24

import django.db.models.deletion
from django.db import migrations, models

import mapquiz.models


class Migration(migrations.Migration):
    dependencies = [
        ('mapquiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='location',
            name='lng',
            field=models.FloatField(null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='uri',
            field=models.OneToOneField(default=mapquiz.models.generate_uri, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='mapquiz.Uri'),
        ),
        migrations.AlterField(
            model_name='location',
            name='uri',
            field=models.OneToOneField(default=mapquiz.models.generate_uri, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='mapquiz.Uri'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='uri',
            field=models.OneToOneField(default=mapquiz.models.generate_uri, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='mapquiz.Uri'),
        ),
        migrations.AlterField(
            model_name='team',
            name='uri',
            field=models.OneToOneField(default=mapquiz.models.generate_uri, on_delete=django.db.models.deletion.CASCADE,
                                       primary_key=True, serialize=False, to='mapquiz.Uri'),
        ),
    ]
